import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main (String[] args) {
		// Gets the two command-line arguments
		int t = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
		// Initailizes a random numbers generator with the given seed value
        Random generator = new Random(seed);  
		double r1 = 0; 
		double avg = 0;
		int fam2 = 0;
		int fam3 = 0;
		int fam4 = 0;
		String msg = "The most common number of children is ";
		for(int i = 0; i < t; i++){
			int boys = 0;
		    int girls = 0;
			int sum = 0;
			while(boys < 1 || girls < 1){ //
				r1 = generator.nextDouble();
				if(r1 <= 0.4){
					boys += 1;
				}else{
					girls += 1;
				}	
				sum++;				
			}
			
			avg += (double) sum;
			if(sum == 2) fam2++;
			else if(sum == 3) fam3++;
			else fam4++;
		}
		avg = avg / t;
		System.out.println("Average: " + avg + " children to get at least one of each gender.");
		System.out.println("Number of families with 2 children: " + fam2);
		System.out.println("Number of families with 3 children: " + fam3);
		System.out.println("Number of families with 4 or more children: " + fam4);
		if(fam2 >= fam3){
			if(fam2 >= fam4) msg += "2";
			else msg += "4 or more";
		}else if(fam3 >= fam4){
			msg += "3";
		}else msg += "4 or more";
		System.out.println(msg + ".");
	}
}
